services:
  configserver:
    image: "kkhandelwal471/myaccount:s6"
    container_name: configserver-ms
    ports:
      - "8071:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  accounts:
    image: "kkhandelwal471/myaccount:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  loans:
    image: "kkhandelwal471/myloans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  cards:
    image: "kkhandelwal471/mycards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
networks:
  bank:
    driver: "bridge"